# Generated by Django 5.2.8 on 2025-11-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='cena_bez_dph',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nazev_produktu',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='popis',
        ),
        migrations.AddField(
            model_name='product',
            name='dph',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=4),
        ),
    ]
