# Generated by Django 5.2.8 on 2025-11-30 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telefon',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefonní číslo musí mít 9–15 číslic a může začínat +.', regex='^\\+?\\d{9,15}$')]),
        ),
    ]
